version:
  ver: "1.0.1"
account:
  "12345678": "admin"
  "12345678000": "member"
authen:
  key: orgcenter
  expiresIn: 24
app:
  port: 9678

url:
  statisticThongkeUrl: "https://localhost:9999/company-manage/v1/statistic/thongke"
  orgInfoUrl: "https://localhost:9999/company-info/v1"
  orgManageCompanyUrl: "https://localhost:9999/company-manage/v1/company"
  orgManageUrl: "https://localhost:9999/company-manage/v1"
