import homeController from './HomeController';
import authController from './AuthController';
import profileController from './ProfileController';
import userController from './userController';
import personalController from './personalController';
import friendController from './friendController';
import chatController from './chatController';
import commentController from './commentController';
import notificationController from './notificationController';
import groupController from './groupController';
import adminController from './admin/adminController';

export const home = homeController;
export const auth = authController;
export const profile = profileController;
export const user = userController;
export const personal = personalController;
export const friend = friendController;
export const chat = chatController;
export const comment = commentController;
export const notification = notificationController;
export const group = groupController;
export const admin = adminController;